export const collectUrls = [
  "https://caiji.huakuiapi.com/inc/apijson_vod.php?ac=detail&pg=",
  "https://apittzy.com/api.php/provide/vod/?ac=detail&pg=",
  "https://api.maozyapi.com/inc/apijson_vod.php?ac=detail&pg=",
  "https://caiji.huakuiapi.com/inc/apijson_vod.php?ac=detail&pg=",
  "https://sewozyapi.com/api.php/provide/vod/?ac=detail&pg=",
  "https://api.apilyzy.com/api.php/provide/vod/?ac=detail&pg=",
  "https://api.apiabzy.com/api.php/provide/vod/?ac=detail&pg=",
  "https://www.siwazyw.cc/api.php/provide/vod/at/json/?ac=detail&pg=",
  "https://kkzy.me/api.php/provide/vod/?ac=detail&pg=",
  "https://sdzyapi.com/api.php/provide/vod/?ac=detail&pg=",
  "https://api.yulecj.com/api.php/provide/vod/?ac=detail&pg=",
  "https://api.guangsuapi.com/api.php/provide/vod/?ac=detail&pg=",
  "https://www.feisuzyapi.com/api.php/provide/vod/?ac=detail&pg=",
  "https://api.tiankongapi.com/api.php/provide/vod/?ac=detail&pg=",
  "https://api.bdxapi.com/api.php/provide/vod/from/bdxm3u8/at/xml/?ac=detail&&pg=",
];
